site_name: Amit Mund
repo_url: https://github.com/Amitmund/amitmund/
site_description: Notes of my learning.
site_author: Amit Kumar Mund

pages:
  - Home: index.md
  - ReadTheDoc: readTheDoc.md
  - Linux: linux.md
  - Linux commands:
    - iptables: iptables.md
  - Cassandra Introduction: cassandra.md
  - Md file example: mdFileExample.md
  - About: about.md
  
markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
 
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
