site_name: Amit Mund
repo_url: https://github.com/Amitmund/amitmund/
site_description: Notes of my learning.
site_author: Amit Kumar Mund

pages:
  - Home: index.md

  - Linux:
    - iptables: linux/iptables.md
    - tcpdump: linux/tcpdump.md
  - Cassandra:
    - Introduction: cassandra/cassandra.md
  - Consul:
    - Consul notes: consul/consul.md
  - Git:
    - Git notes: git/git.md
  - ReadTheDocRelated:
    - Notes on readthedoc: markdown/readTheDoc.md
    - Example of Markdown: markdown/mdFileExample.md
  - About: about.md
  
markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
 
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        
extra_css:
    - css/extra.css

plugins:
    - search
