site_name: Amit Mund
nav:
    - Home: index.md
    - ReadTheDoc: readTheDoc.md
    - Linux: linux.md
        - Linux Commands: linuxCommands.md
            - iptables: iptables.md
    - Cassandra: cassandra.md
        - Cassandra Interview Related Questions: cassandraInterviewQuestions.md
    - About: about.md
theme: readthedocs
