site_name: 		Amit Mund
repo_url: 		https://github.com/Amitmund/amitmund/
site_description: 	Notes of my learning.
site_author: 		Amit Kumar Mund

 
theme: readthedocs

nav:
    - Home: index.md
    - ReadTheDoc: readTheDoc.md
    - Linux: 
	- Linux: linux/linux.md
        - Linux Commands:
            - iptables: iptables.md
    - Cassandra: 
	- Cassandra: cassandra/cassandra.md
        - Cassandra Interview Related Questions: cassandraInterviewQuestions.md
    - About: about.md
